spring:
  application:
    name: book-recommender-api
  ai:
    ollama:
      base-url: http://localhost:11434
      chat:
        options:
          model: mistral
          temperature: 0.7
      embedding:
        options:
          model: nomic-embed-text

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: app_user
    password: 123456
